version: "3"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
     - "3030:3030"
     - "4040:4040"
     - "5050:5050"
    volumes:
     - ./server:/app
     - /app/node_modules
    networks: 
     - app-network
    environment:
     - NODE_ENV=development
    command: npm run dev


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
     - "8080:8080"
    volumes: 
     - ./client:/app
     - /app/node_modules
    environment:
     - NODE_ENV=development
    depends_on: 
     - server
    command: npm run serve

volumes: 
  app_db_volume:

networks: 
  app-network: