module.exports.Successful_Login = "Login Successfully"
module.exports.User_logged_In = "Already logged in!"
module.exports.Server_Problem = "Problem Detected In Server"
module.exports.Data_Found = "Data Found"
module.exports.Data_Not_Found = "Data Not Found"
module.exports.Bid_Success = "Successfully bid"
module.exports.Already_Bided = "Already bid for the product"
module.exports.Bid_Price_Limit_Updated = "Bid Price Limit Updated"
module.exports.Update_Failed = "Update Failed"
module.exports.Bid_Start_Failed = "Bidding has not started yet"
module.exports.Bid_Time_Over = "Bidding Time Over"
module.exports.Exciding_Bid_Amount = "Exciding the bid amount"

